spring:
  application:
    name: app
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: HikariPool-Oracle
      auto-commit: true
      connection-test-query: SELECT 1 FROM DUAL
      transaction-isolation: TRANSACTION_READ_COMMITTED
    url: jdbc:oracle:thin:@//localhost:1521/FREE
    username: system
    password: 123Mudar
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
oracle:
  username: rafael.cardoso@synchro.com.br
  password: VGR3khe!kux8erf2rbq
  url: https://eksz-test.fa.la1.oraclecloud.com/xmlpserver/services/v2/ReportService

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        liveness:
          include: ping,diskSpace
      validate-group-membership: false
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.SQL_SLOW: INFO
    org.hibernate.cache: DEBUG
    org.apache.camel: DEBUG
    org.springframework.orm.jpa: DEBUG
    com.zaxxer.hikari: DEBUG