spring:
  application:
    name: app
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: ${oracle.username}
    password: ${oracle.password}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
oracle:
  username: user
  password: pass
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        liveness:
          include: ping,diskSpace
      validate-group-membership: false
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
